# Generated by Django 4.0 on 2022-01-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_value',
            field=models.FloatField(default=0, verbose_name='Сумма бюджета'),
        ),
        migrations.AddField(
            model_name='budget',
            name='last_rel',
            field=models.IntegerField(default=80),
        ),
    ]
