# Generated by Django 4.0 on 2021-12-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='avatar',
            field=models.ImageField(upload_to='avatars/clients', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='specialistprofile',
            name='avatar',
            field=models.ImageField(upload_to='avatars/specialists', verbose_name='Аватар'),
        ),
    ]
