# Generated by Django 4.0 on 2021-12-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_clientprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('client', 'Клиент'), ('specialist', 'Специалист'), ('photographer', 'Фотограф')], default='client', max_length=155, verbose_name='Тип пользователя'),
        ),
        migrations.DeleteModel(
            name='SpecialistProfile',
        ),
    ]
