# Generated by Django 4.0 on 2021-12-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_type_delete_specialistprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(default='client', max_length=155, verbose_name='Тип пользователя'),
        ),
    ]
