# Generated by Django 4.0 on 2022-03-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_clientprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг пользователя'),
        ),
    ]
