# Generated by Django 4.0 on 2022-05-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_clientprofile_is_active_clientprofile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='uuid',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='User unique ID'),
        ),
    ]
