# Generated by Django 4.0 on 2022-05-24 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_clientprofile_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='uuid',
        ),
    ]
