# Generated by Django 4.0 on 2022-06-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_blocklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Название района UZ'),
        ),
    ]
