# Generated by Django 4.0 on 2021-12-28 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_alter_clientprofile_options_alter_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('photographer', 'Фотограф'), ('artist', 'Артист, Шоу программа'), ('transport', 'Транспорт'), ('music', 'Музыканты, Dj'), ('presenter', 'Ведущий'), ('invitation', 'Пригласительные'), ('cake', 'Торт'), ('dress', 'Платье'), ('ring', 'Кольца'), ('bouquet', 'Букет'), ('decor', 'Декор, оформление'), ('costume', 'Костюм'), ('accessories', 'Аксуссуары'), ('stylist', 'Стилист, Визажист'), ('photostudio', 'Фотостудия'), ('dance', 'Танец'), ('agency', 'Агенство')], default=None, max_length=15)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания тендера')),
                ('on_date', models.DateField(verbose_name='Дата события')),
                ('budget', models.FloatField(verbose_name='Бюджет')),
                ('slug', models.SlugField(default='<django.db.models.fields.related.ForeignKey>tender', max_length=200, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor', to='account.user')),
                ('response', models.ManyToManyField(null=True, related_name='responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тендер',
                'verbose_name_plural': 'Тендеры',
            },
        ),
    ]
