# Generated by Django 4.0 on 2021-12-28 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_clientprofile_options_alter_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor', to='account.user'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='response',
            field=models.ManyToManyField(blank=True, related_name='responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tender',
            name='slug',
            field=models.SlugField(blank=True, default='sometender', max_length=200, unique=True),
        ),
    ]
