# Generated by Django 4.0 on 2021-12-29 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_clientprofile_avatar'),
        ('tender', '0003_remove_tender_response_alter_tender_author_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='account.user'),
        ),
    ]
