# Generated by Django 4.0 on 2022-01-10 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0004_alter_response_from_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='tender.tender'),
        ),
    ]
