# Generated by Django 4.0 on 2022-02-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0005_alter_response_tender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-created'], 'verbose_name': 'Отклик', 'verbose_name_plural': 'Отклики'},
        ),
        migrations.AlterModelOptions(
            name='tender',
            options={'ordering': ['-create_date'], 'verbose_name': 'Тендер', 'verbose_name_plural': 'Тендеры'},
        ),
        migrations.AddField(
            model_name='response',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
