# Generated by Django 4.0 on 2022-03-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0008_alter_tender_budget_alter_tender_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='service',
            field=models.CharField(choices=[('photographer', 'Фотограф'), ('artist', 'Артист, Шоу программа'), ('transport', 'Транспорт'), ('music', 'Музыканты, Dj'), ('presenter', 'Ведущий'), ('invitation', 'Пригласительные'), ('cake', 'Торт'), ('dress', 'Платье'), ('ring', 'Кольца'), ('bouquet', 'Букет'), ('decor', 'Декор, оформление'), ('costume', 'Костюм'), ('accessories', 'Аксессуары'), ('stylist', 'Стилист, Визажист'), ('photostudio', 'Фотостудия'), ('dance', 'Танец'), ('agency', 'Агенство'), ('videographer', 'Видеограф')], default=None, max_length=15, verbose_name='Услуга'),
        ),
    ]
