# Generated by Django 4.0 on 2022-09-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0011_alter_tender_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='service',
            field=models.CharField(choices=[('restaurant', 'Банкетный зал и ресторан'), ('registryoffice', 'Дворец бракосечетания и ЗАГС'), ('photostudio', 'Площадка для фотосессий'), ('decor', 'Оформление и декор'), ('transport', 'Транспортные услуги'), ('photographer', 'Фотограф'), ('videographer', 'Видеограф'), ('presenter', 'Ведущий и тамада'), ('music', 'Музыканты и Dj'), ('artist', 'Шоу программа и Артисты'), ('cake', 'Свадебный торт'), ('dress', 'Свадебное платье'), ('costume', 'Свадебный костюм'), ('ring', 'Обручальные кольца'), ('bouquet', 'Букет невесты'), ('stylist', 'Стилист и визажист'), ('accessories', 'Свадебные аксессуары'), ('dance', 'Свадебный танец'), ('invitation', 'Пригласительные'), ('agency', 'Свадебное агентство')], default=None, max_length=15, verbose_name='Услуга'),
        ),
    ]
