# Generated by Django 4.0 on 2021-12-24 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_alter_user_type_delete_specialistprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название услуги')),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=155, verbose_name='Имя и Фамилия')),
                ('about', models.TextField(verbose_name='О себе')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('price_per_hour', models.FloatField(verbose_name='Цена за час')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/specialists', verbose_name='Аватар')),
                ('phone', models.IntegerField(verbose_name='Телефон')),
                ('telegram', models.CharField(max_length=50, verbose_name='Телеграм')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
