# Generated by Django 4.0 on 2022-02-10 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_accessories_created_accessories_is_pro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Тип заведения')),
            ],
            options={
                'verbose_name': 'Тип заведения',
                'verbose_name_plural': 'Типы заведений',
            },
        ),
        migrations.AlterModelOptions(
            name='accessories',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Свадебные аксессуары', 'verbose_name_plural': 'Свадебные аксессуары'},
        ),
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Свадебное агенство', 'verbose_name_plural': 'Свадебные агенства'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Шоу программа, артист', 'verbose_name_plural': 'Шоу программы, артисты'},
        ),
        migrations.AlterModelOptions(
            name='bouquet',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Свадебный букет', 'verbose_name_plural': 'Свадебные букеты'},
        ),
        migrations.AlterModelOptions(
            name='cake',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Свадебный торт', 'verbose_name_plural': 'Свадебные торты'},
        ),
        migrations.AlterModelOptions(
            name='costume',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Свадебный костюм', 'verbose_name_plural': 'Свадебные костюмы'},
        ),
        migrations.AlterModelOptions(
            name='dance',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Свадебный танец', 'verbose_name_plural': 'Свадебный танец'},
        ),
        migrations.AlterModelOptions(
            name='decor',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Оформление и декор', 'verbose_name_plural': 'Оформление и декор'},
        ),
        migrations.AlterModelOptions(
            name='dress',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Свадебное платье', 'verbose_name_plural': 'Свадебные платья'},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Пригласительное', 'verbose_name_plural': 'Пригласительные'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Музыкальная группа, DJ', 'verbose_name_plural': 'Музыкальные группы, DJ'},
        ),
        migrations.AlterModelOptions(
            name='photographer',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Фотограф', 'verbose_name_plural': 'Фотографы'},
        ),
        migrations.AlterModelOptions(
            name='photostudio',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Фотостудия', 'verbose_name_plural': 'Фотостудии'},
        ),
        migrations.AlterModelOptions(
            name='presenter',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Ведущий', 'verbose_name_plural': 'Ведущие'},
        ),
        migrations.AlterModelOptions(
            name='registryoffice',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Дворец бракосочетания, ЗАГС', 'verbose_name_plural': 'Дворцы бракосочтания, ЗАГСы'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Банкетный зал, ретсоран', 'verbose_name_plural': 'Банкетные залы, рестораны'},
        ),
        migrations.AlterModelOptions(
            name='ring',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Свадебное кольцо', 'verbose_name_plural': 'Свадебные кольца'},
        ),
        migrations.AlterModelOptions(
            name='stylist',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Стилист, визажист', 'verbose_name_plural': 'Стилисты, визажисты'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Транспорт', 'verbose_name_plural': 'Транспорт'},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.restauranttype', verbose_name='Тип заведения'),
        ),
    ]
