# Generated by Django 4.0 on 2022-02-11 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_clientprofile_phone'),
        ('services', '0013_alter_review_options_review_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryoffice',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.district', verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='registryoffice',
            name='type',
            field=models.CharField(choices=[('visiting', 'Выездная'), ('not_visiting', 'Не выездная')], max_length=50, null=True),
        ),
    ]
