# Generated by Django 4.0 on 2022-02-11 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_registryoffice_location_registryoffice_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registryoffice',
            name='on_departure',
        ),
    ]
