# Generated by Django 4.0 on 2022-02-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_remove_registryoffice_on_departure'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryoffice',
            name='facebook',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AddField(
            model_name='registryoffice',
            name='instagram',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AddField(
            model_name='registryoffice',
            name='telegram',
            field=models.CharField(blank=True, max_length=155),
        ),
    ]
