# Generated by Django 4.0 on 2022-02-14 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_clientprofile_phone'),
        ('services', '0020_alter_accessories_accessories_type_alter_artist_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=155, verbose_name='Имя и Фамилия')),
                ('about', models.TextField(verbose_name='О себе')),
                ('price', models.FloatField(null=True, verbose_name='Цена')),
                ('price_per_hour', models.FloatField(null=True, verbose_name='Цена за час')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/videographers', verbose_name='Аватар')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон')),
                ('telegram', models.CharField(max_length=50, verbose_name='Телеграм')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('is_pro', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'verbose_name': 'Видеограф',
                'verbose_name_plural': 'Видеографы',
                'ordering': ['-is_pro', '-created'],
            },
        ),
    ]
