# Generated by Django 4.0 on 2022-02-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_rename_full_name_photographer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photostudio',
            name='type',
            field=models.CharField(choices=[('1', 'Фотостудии'), ('2', 'Локации для фотосессий')], max_length=50, null=True),
        ),
    ]
