# Generated by Django 4.0 on 2022-02-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_photostudio_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='service_type',
            field=models.CharField(choices=[('1', 'Свадебная причёска'), ('2', 'Свадебный маникюр'), ('3', 'Свадебный макияж')], max_length=50, null=True, verbose_name='Вид услуги'),
        ),
    ]
