# Generated by Django 4.0 on 2022-03-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_review_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAdditionalFeeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название услуги')),
            ],
            options={
                'verbose_name': 'Музыканты - Услуга за доп плату',
                'verbose_name_plural': 'Музыканты - Услуги за доп плату',
            },
        ),
        migrations.CreateModel(
            name='MusicBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Музыканты - Преимущество заведения',
                'verbose_name_plural': 'Музыканты - Преимущества заведения',
            },
        ),
        migrations.CreateModel(
            name='MusicPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Музыканты - Способ оплаты',
                'verbose_name_plural': 'Музыканты - Способы оплаты',
            },
        ),
        migrations.CreateModel(
            name='PhotographerAdditionalFeeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название услуги')),
            ],
            options={
                'verbose_name': 'Фотограф - Услуга за доп плату',
                'verbose_name_plural': 'Фотограф - Услуги за доп плату',
            },
        ),
        migrations.CreateModel(
            name='PhotographerBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Фотограф - Преимущество заведения',
                'verbose_name_plural': 'Фотограф - Преимущества заведения',
            },
        ),
        migrations.CreateModel(
            name='PhotographerPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Фотограф - Способ оплаты',
                'verbose_name_plural': 'Фотограф - Способы оплаты',
            },
        ),
        migrations.CreateModel(
            name='PhotostudioAdditionalFeeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название услуги')),
            ],
            options={
                'verbose_name': 'Фотостудии - Услуга за доп плату',
                'verbose_name_plural': 'Фотостудии - Услуги за доп плату',
            },
        ),
        migrations.CreateModel(
            name='PhotostudioBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Фотостудии - Преимущество заведения',
                'verbose_name_plural': 'Фотостудии - Преимущества заведения',
            },
        ),
        migrations.CreateModel(
            name='PhotostudioPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Фотостудии - Способ оплаты',
                'verbose_name_plural': 'Фотостудии - Способы оплаты',
            },
        ),
        migrations.CreateModel(
            name='PresenterAdditionalFeeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название услуги')),
            ],
            options={
                'verbose_name': 'Ведущие - Услуга за доп плату',
                'verbose_name_plural': 'Ведущие - Услуги за доп плату',
            },
        ),
        migrations.CreateModel(
            name='PresenterBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ведущие - Преимущество заведения',
                'verbose_name_plural': 'Ведущие - Преимущества заведения',
            },
        ),
        migrations.CreateModel(
            name='PresenterPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ведущие - Способ оплаты',
                'verbose_name_plural': 'Ведущие - Способы оплаты',
            },
        ),
        migrations.CreateModel(
            name='VideographerAdditionalFeeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название услуги')),
            ],
            options={
                'verbose_name': 'Видеограф - Услуга за доп плату',
                'verbose_name_plural': 'Видеограф - Услуги за доп плату',
            },
        ),
        migrations.CreateModel(
            name='VideographerBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Видеограф - Преимущество заведения',
                'verbose_name_plural': 'Видеограф - Преимущества заведения',
            },
        ),
        migrations.CreateModel(
            name='VideographerPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Видеограф - Способ оплаты',
                'verbose_name_plural': 'Видеограф - Способы оплаты',
            },
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Банкетный зал, ресторан', 'verbose_name_plural': 'Банкетные залы, рестораны'},
        ),
        migrations.AlterModelOptions(
            name='restaurantadditionalfeeservice',
            options={'verbose_name': 'Ресторан - Услуга за доп плату', 'verbose_name_plural': 'Ресторан - Услуги за доп плату'},
        ),
        migrations.AlterModelOptions(
            name='restaurantbenefits',
            options={'verbose_name': 'Ресторан - Преимущество заведения', 'verbose_name_plural': 'Ресторан - Преимущества заведения'},
        ),
        migrations.AlterModelOptions(
            name='restaurantpaymentmethod',
            options={'verbose_name': 'Ресторан - Способ оплаты', 'verbose_name_plural': 'Ресторан - Способы оплаты'},
        ),
        migrations.AddField(
            model_name='music',
            name='additional_services',
            field=models.ManyToManyField(to='services.MusicAdditionalFeeService', verbose_name='Услуги за доп плату'),
        ),
        migrations.AddField(
            model_name='music',
            name='benefits',
            field=models.ManyToManyField(to='services.MusicBenefits', verbose_name='Преимущества'),
        ),
        migrations.AddField(
            model_name='music',
            name='payment',
            field=models.ManyToManyField(to='services.MusicPaymentMethod', verbose_name='Способы оплаты'),
        ),
        migrations.AddField(
            model_name='photographer',
            name='additional_services',
            field=models.ManyToManyField(to='services.PhotographerAdditionalFeeService', verbose_name='Услуги за доп плату'),
        ),
        migrations.AddField(
            model_name='photographer',
            name='benefits',
            field=models.ManyToManyField(to='services.PhotographerBenefits', verbose_name='Преимущества'),
        ),
        migrations.AddField(
            model_name='photographer',
            name='payment',
            field=models.ManyToManyField(to='services.PhotographerPaymentMethod', verbose_name='Способы оплаты'),
        ),
        migrations.AddField(
            model_name='photostudio',
            name='additional_services',
            field=models.ManyToManyField(to='services.PhotostudioAdditionalFeeService', verbose_name='Услуги за доп плату'),
        ),
        migrations.AddField(
            model_name='photostudio',
            name='benefits',
            field=models.ManyToManyField(to='services.PhotostudioBenefits', verbose_name='Преимущества'),
        ),
        migrations.AddField(
            model_name='photostudio',
            name='payment',
            field=models.ManyToManyField(to='services.PhotostudioPaymentMethod', verbose_name='Способы оплаты'),
        ),
        migrations.AddField(
            model_name='presenter',
            name='additional_services',
            field=models.ManyToManyField(to='services.PresenterAdditionalFeeService', verbose_name='Услуги за доп плату'),
        ),
        migrations.AddField(
            model_name='presenter',
            name='benefits',
            field=models.ManyToManyField(to='services.PresenterBenefits', verbose_name='Преимущества'),
        ),
        migrations.AddField(
            model_name='presenter',
            name='payment',
            field=models.ManyToManyField(to='services.PresenterPaymentMethod', verbose_name='Способы оплаты'),
        ),
        migrations.AddField(
            model_name='videographer',
            name='additional_services',
            field=models.ManyToManyField(to='services.VideographerAdditionalFeeService', verbose_name='Услуги за доп плату'),
        ),
        migrations.AddField(
            model_name='videographer',
            name='benefits',
            field=models.ManyToManyField(to='services.VideographerBenefits', verbose_name='Преимущества'),
        ),
        migrations.AddField(
            model_name='videographer',
            name='payment',
            field=models.ManyToManyField(to='services.VideographerPaymentMethod', verbose_name='Способы оплаты'),
        ),
    ]
