# Generated by Django 4.0 on 2022-03-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_musicadditionalfeeservice_musicbenefits_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registryoffice',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Дворец бракосочетания, ЗАГС', 'verbose_name_plural': 'Дворцы бракосочетания, ЗАГСы'},
        ),
    ]
