# Generated by Django 4.0 on 2022-03-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_alter_registryoffice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photostudio',
            options={'ordering': ['-is_pro', '-created'], 'verbose_name': 'Площадка для фотосессий', 'verbose_name_plural': 'Площадки для фотосессий'},
        ),
        migrations.AlterField(
            model_name='costume',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Начальная цена'),
        ),
    ]
