# Generated by Django 4.0 on 2022-03-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_alter_photostudio_options_alter_costume_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='price_per_hour',
            field=models.IntegerField(null=True, verbose_name='Цена за час'),
        ),
    ]
