# Generated by Django 4.0 on 2022-03-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_alter_photographer_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Начальная цена'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Начальная цена'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='price_per_kg',
            field=models.IntegerField(null=True, verbose_name='Цена за кг'),
        ),
        migrations.AlterField(
            model_name='dance',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена '),
        ),
        migrations.AlterField(
            model_name='decor',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Минимальная цена украшения зала'),
        ),
        migrations.AlterField(
            model_name='dress',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Начальная цена'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Начальная цена'),
        ),
        migrations.AlterField(
            model_name='music',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена за выступление'),
        ),
        migrations.AlterField(
            model_name='music',
            name='price_per_evening',
            field=models.IntegerField(null=True, verbose_name='Цена за вечер'),
        ),
        migrations.AlterField(
            model_name='photostudio',
            name='price_per_hour',
            field=models.IntegerField(null=True, verbose_name='Цена за час'),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='price_per_hour',
            field=models.IntegerField(null=True, verbose_name='Цена за час'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='average_check',
            field=models.IntegerField(verbose_name='Средний чек'),
        ),
        migrations.AlterField(
            model_name='ring',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='stylist',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена '),
        ),
        migrations.AlterField(
            model_name='transport',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='videographer',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='videographer',
            name='price_per_hour',
            field=models.IntegerField(null=True, verbose_name='Цена за час'),
        ),
    ]
