# Generated by Django 4.0 on 2022-03-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_alter_accessories_price_alter_agency_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='composition',
            field=models.CharField(choices=[('solo', 'Соло'), ('duet', 'Дуэт'), ('group', 'Группа'), ('dj', 'Dj')], max_length=50, null=True, verbose_name='Исполнители'),
        ),
        migrations.AlterField(
            model_name='music',
            name='language',
            field=models.ManyToManyField(to='services.Language', verbose_name='Язык исполнения песен'),
        ),
    ]
