# Generated by Django 4.0 on 2022-03-28 05:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_alter_music_composition_alter_music_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costume',
            name='condition',
            field=models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Арендa')], max_length=50, null=True, verbose_name='Вид сделки'),
        ),
        migrations.AlterField(
            model_name='dress',
            name='condition',
            field=models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Арендa')], max_length=50, null=True, verbose_name='Вид сделки'),
        ),
        migrations.AlterField(
            model_name='photostudio',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='composition',
            field=models.CharField(choices=[('solo', 'Соло'), ('duet', 'Дуэт')], max_length=50, null=True, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='registryoffice',
            name='type',
            field=models.CharField(choices=[('visiting', 'Выездная'), ('not_visiting', 'Невыездная')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ring',
            name='type',
            field=models.CharField(choices=[('business', 'Ювелирный магазин'), ('private', 'Индивидуальные услуги')], max_length=50, null=True),
        ),
    ]
