# Generated by Django 4.0 on 2022-03-28 05:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_alter_costume_condition_alter_dress_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='about',
            field=ckeditor.fields.RichTextField(verbose_name='О себе'),
        ),
    ]
