# Generated by Django 4.0 on 2022-03-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_alter_accessories_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='facebook',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AddField(
            model_name='photographer',
            name='instagram',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AddField(
            model_name='videographer',
            name='facebook',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AddField(
            model_name='videographer',
            name='instagram',
            field=models.CharField(blank=True, max_length=155),
        ),
    ]
