# Generated by Django 4.0 on 2022-03-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_photographer_facebook_photographer_instagram_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Фото/видео', 'verbose_name_plural': 'Фото/видео'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='portfolio/images'),
        ),
    ]
