# Generated by Django 4.0 on 2022-03-31 05:51

from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_alter_image_options_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='portfolio/images', upload_to=services.models.user_directory_path)),
                ('content_type', models.CharField(max_length=155)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='services.portfolio')),
            ],
            options={
                'verbose_name': 'Фото/видео',
                'verbose_name_plural': 'Фото/видео',
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
