# Generated by Django 4.0 on 2022-03-31 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_file_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='price',
        ),
        migrations.RemoveField(
            model_name='music',
            name='price_per_evening',
        ),
    ]
