# Generated by Django 4.0 on 2022-04-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0040_remove_cake_price_remove_music_price_per_evening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='price',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='price',
        ),
        migrations.AlterField(
            model_name='dress',
            name='dress_type',
            field=models.CharField(choices=[('bouffant', 'Пышное'), ('straight', 'Прямое')], max_length=50, null=True, verbose_name='Тип платья'),
        ),
        migrations.AlterField(
            model_name='dress',
            name='type',
            field=models.CharField(choices=[('business', 'Компания'), ('private', 'Индивидуальные услуги')], max_length=50, null=True, verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='ring',
            name='type',
            field=models.CharField(choices=[('business', 'Компании'), ('private', 'Индивидуальные услуги')], max_length=50, null=True),
        ),
    ]
