# Generated by Django 4.0 on 2022-04-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_remove_agency_price_remove_invitation_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='phone2',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №2'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='phone3',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №3'),
        ),
        migrations.AddField(
            model_name='agency',
            name='phone2',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №2'),
        ),
        migrations.AddField(
            model_name='agency',
            name='phone3',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №3'),
        ),
        migrations.AddField(
            model_name='artist',
            name='phone2',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №2'),
        ),
        migrations.AddField(
            model_name='artist',
            name='phone3',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №3'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='phone2',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №2'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='phone3',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №3'),
        ),
        migrations.AddField(
            model_name='cake',
            name='phone2',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №2'),
        ),
        migrations.AddField(
            model_name='cake',
            name='phone3',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №3'),
        ),
        migrations.AddField(
            model_name='costume',
            name='phone2',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №2'),
        ),
        migrations.AddField(
            model_name='costume',
            name='phone3',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №3'),
        ),
        migrations.AddField(
            model_name='dance',
            name='phone2',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №2'),
        ),
        migrations.AddField(
            model_name='dance',
            name='phone3',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №3'),
        ),
        migrations.AddField(
            model_name='decor',
            name='phone2',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №2'),
        ),
        migrations.AddField(
            model_name='decor',
            name='phone3',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №3'),
        ),
        migrations.AddField(
            model_name='dress',
            name='phone2',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №2'),
        ),
        migrations.AddField(
            model_name='dress',
            name='phone3',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №3'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='phone2',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №2'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='phone3',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №3'),
        ),
        migrations.AddField(
            model_name='music',
            name='phone2',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №2'),
        ),
        migrations.AddField(
            model_name='music',
            name='phone3',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №3'),
        ),
        migrations.AddField(
            model_name='photographer',
            name='phone2',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №2'),
        ),
        migrations.AddField(
            model_name='photographer',
            name='phone3',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №3'),
        ),
        migrations.AddField(
            model_name='photostudio',
            name='phone2',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №2'),
        ),
        migrations.AddField(
            model_name='photostudio',
            name='phone3',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №3'),
        ),
        migrations.AddField(
            model_name='presenter',
            name='phone2',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №2'),
        ),
        migrations.AddField(
            model_name='presenter',
            name='phone3',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №3'),
        ),
        migrations.AddField(
            model_name='registryoffice',
            name='phone2',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №2'),
        ),
        migrations.AddField(
            model_name='registryoffice',
            name='phone3',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №3'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone2',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №2'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone3',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №3'),
        ),
        migrations.AddField(
            model_name='ring',
            name='phone2',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №2'),
        ),
        migrations.AddField(
            model_name='ring',
            name='phone3',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №3'),
        ),
        migrations.AddField(
            model_name='stylist',
            name='phone2',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №2'),
        ),
        migrations.AddField(
            model_name='stylist',
            name='phone3',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №3'),
        ),
        migrations.AddField(
            model_name='transport',
            name='phone2',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №2'),
        ),
        migrations.AddField(
            model_name='transport',
            name='phone3',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №3'),
        ),
        migrations.AddField(
            model_name='videographer',
            name='phone2',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №2'),
        ),
        migrations.AddField(
            model_name='videographer',
            name='phone3',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон №3'),
        ),
    ]
