# Generated by Django 4.0 on 2022-04-19 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0043_remove_dress_dress_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costume',
            name='rent',
        ),
    ]
