# Generated by Django 4.0 on 2022-05-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0044_remove_costume_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='additional_services',
            field=models.ManyToManyField(blank=True, to='services.MusicAdditionalFeeService', verbose_name='Услуги за доп плату'),
        ),
        migrations.AlterField(
            model_name='music',
            name='benefits',
            field=models.ManyToManyField(blank=True, to='services.MusicBenefits', verbose_name='Преимущества'),
        ),
        migrations.AlterField(
            model_name='music',
            name='payment',
            field=models.ManyToManyField(blank=True, to='services.MusicPaymentMethod', verbose_name='Способы оплаты'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='additional_services',
            field=models.ManyToManyField(blank=True, to='services.PhotographerAdditionalFeeService', verbose_name='Услуги за доп плату'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='benefits',
            field=models.ManyToManyField(blank=True, to='services.PhotographerBenefits', verbose_name='Преимущества'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='payment',
            field=models.ManyToManyField(blank=True, to='services.PhotographerPaymentMethod', verbose_name='Способы оплаты'),
        ),
        migrations.AlterField(
            model_name='photostudio',
            name='additional_services',
            field=models.ManyToManyField(blank=True, to='services.PhotostudioAdditionalFeeService', verbose_name='Услуги за доп плату'),
        ),
        migrations.AlterField(
            model_name='photostudio',
            name='benefits',
            field=models.ManyToManyField(blank=True, to='services.PhotostudioBenefits', verbose_name='Преимущества'),
        ),
        migrations.AlterField(
            model_name='photostudio',
            name='payment',
            field=models.ManyToManyField(blank=True, to='services.PhotostudioPaymentMethod', verbose_name='Способы оплаты'),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='additional_services',
            field=models.ManyToManyField(blank=True, to='services.PresenterAdditionalFeeService', verbose_name='Услуги за доп плату'),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='benefits',
            field=models.ManyToManyField(blank=True, to='services.PresenterBenefits', verbose_name='Преимущества'),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='payment',
            field=models.ManyToManyField(blank=True, to='services.PresenterPaymentMethod', verbose_name='Способы оплаты'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='additional_services',
            field=models.ManyToManyField(blank=True, to='services.RestaurantAdditionalFeeService', verbose_name='Услуги за доп плату'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='benefits',
            field=models.ManyToManyField(blank=True, to='services.RestaurantBenefits', verbose_name='Преимущества'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='payment',
            field=models.ManyToManyField(blank=True, to='services.RestaurantPaymentMethod', verbose_name='Способы оплаты'),
        ),
        migrations.AlterField(
            model_name='videographer',
            name='additional_services',
            field=models.ManyToManyField(blank=True, to='services.VideographerAdditionalFeeService', verbose_name='Услуги за доп плату'),
        ),
        migrations.AlterField(
            model_name='videographer',
            name='benefits',
            field=models.ManyToManyField(blank=True, to='services.VideographerBenefits', verbose_name='Преимущества'),
        ),
        migrations.AlterField(
            model_name='videographer',
            name='payment',
            field=models.ManyToManyField(blank=True, to='services.VideographerPaymentMethod', verbose_name='Способы оплаты'),
        ),
    ]
