# Generated by Django 4.0 on 2022-05-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0046_alter_accessories_phone2_alter_accessories_phone3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicadditionalfeeservice',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Название услуги UZ'),
        ),
        migrations.AddField(
            model_name='musicbenefits',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Название UZ'),
        ),
        migrations.AddField(
            model_name='musicpaymentmethod',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Название UZ'),
        ),
        migrations.AddField(
            model_name='photographeradditionalfeeservice',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Название услуги UZ'),
        ),
        migrations.AddField(
            model_name='photographerbenefits',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Название UZ'),
        ),
        migrations.AddField(
            model_name='photographerpaymentmethod',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Название UZ'),
        ),
        migrations.AddField(
            model_name='photostudioadditionalfeeservice',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Название услуги UZ'),
        ),
        migrations.AddField(
            model_name='photostudiobenefits',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Название UZ'),
        ),
        migrations.AddField(
            model_name='photostudiopaymentmethod',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Название UZ'),
        ),
        migrations.AddField(
            model_name='presenteradditionalfeeservice',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Название услуги UZ'),
        ),
        migrations.AddField(
            model_name='presenterbenefits',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Название UZ'),
        ),
        migrations.AddField(
            model_name='presenterpaymentmethod',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Название UZ'),
        ),
        migrations.AddField(
            model_name='restaurantadditionalfeeservice',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Название услуги UZ'),
        ),
        migrations.AddField(
            model_name='restaurantbenefits',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Название UZ'),
        ),
        migrations.AddField(
            model_name='restaurantpaymentmethod',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Название UZ'),
        ),
        migrations.AddField(
            model_name='videographeradditionalfeeservice',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Название услуги UZ'),
        ),
        migrations.AddField(
            model_name='videographerbenefits',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Название UZ'),
        ),
        migrations.AddField(
            model_name='videographerpaymentmethod',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Название UZ'),
        ),
    ]
