# Generated by Django 4.0 on 2022-06-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0047_musicadditionalfeeservice_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartype',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Тип авто UZ'),
        ),
        migrations.AddField(
            model_name='kitchentype',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Название кухни UZ'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Язык UZ'),
        ),
        migrations.AddField(
            model_name='restauranttype',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Тип заведения UZ'),
        ),
        migrations.AddField(
            model_name='showtype',
            name='name_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Название UZ'),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Тип авто'),
        ),
        migrations.AlterField(
            model_name='showtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
