# Generated by Django 4.0 on 2022-06-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0048_cartype_name_uz_kitchentype_name_uz_language_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='address_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Адрес UZ'),
        ),
        migrations.AddField(
            model_name='agency',
            name='address_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Адрес UZ'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='address_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Адрес UZ'),
        ),
        migrations.AddField(
            model_name='cake',
            name='address_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Адрес UZ'),
        ),
        migrations.AddField(
            model_name='costume',
            name='address_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Адрес UZ'),
        ),
        migrations.AddField(
            model_name='dance',
            name='address_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Адрес UZ'),
        ),
        migrations.AddField(
            model_name='dress',
            name='address_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Адрес UZ'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='address_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Адрес UZ'),
        ),
        migrations.AddField(
            model_name='photostudio',
            name='address_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Адрес UZ'),
        ),
        migrations.AddField(
            model_name='registryoffice',
            name='address_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Адрес UZ'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Адрес UZ'),
        ),
        migrations.AddField(
            model_name='ring',
            name='address_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Адрес UZ'),
        ),
        migrations.AddField(
            model_name='stylist',
            name='address_uz',
            field=models.CharField(blank=True, max_length=155, verbose_name='Адрес UZ'),
        ),
    ]
