from django.urls import path
from . import views

app_name = 'services'
urlpatterns = [
    path('photographers/', views.PhotographerList.as_view(), name='photographer_list'),
    path('photographer/<slug:slug>', views.PhotographerDetail.as_view(), name='photographer_detail'),
    path('restaurants/', views.RestaurantList.as_view(), name='restaurant_list'),
    path('restaurant/<slug:slug>', views.RestaurantDetail.as_view(), name='restaurant_detail'),
    path('artists/', views.ArtistList.as_view(), name='artist_list'),
    path('artist/<slug:slug>', views.ArtistDetail.as_view(), name='artist_detail'),
    path('transports/', views.TransportList.as_view(), name='transport_list'),
    path('transport/<slug:slug>', views.TransportDetail.as_view(), name='transport_detail'),
    path('music/', views.MusicList.as_view(), name='music_list'),
    path('music/<slug:slug>', views.MusicDetail.as_view(), name='music_detail'),
    path('presenters/', views.PresenterList.as_view(), name='presenter_list'),
    path('presenter/<slug:slug>', views.PresenterDetail.as_view(), name='presenter_detail'),
    path('registry-offices/', views.RegistryOfficeList.as_view(), name='registryoffice_list'),
    path('registry-office/<slug:slug>', views.RegistryOfficeDetail.as_view(), name='registryoffice_detail'),
    path('invitations/', views.InvitationList.as_view(), name='invitation_list'),
    path('invitations/<slug:slug>', views.InvitationDetail.as_view(), name='invitation_detail'),
    path('cakes/', views.CakeList.as_view(), name='cake_list'),
    path('cake/<slug:slug>', views.CakeDetail.as_view(), name='cake_detail'),
    path('dresses/', views.DressList.as_view(), name='dress_list'),
    path('dress/<slug:slug>', views.DressDetail.as_view(), name='dress_detail'),
    path('rings/', views.RingList.as_view(), name='ring_list'),
    path('ring/<slug:slug>', views.RingDetail.as_view(), name='ring_detail'),
    path('bouquets/', views.BouquetList.as_view(), name='bouquet_list'),
    path('bouquet/<slug:slug>', views.BouquetDetail.as_view(), name='bouquet_detail'),
    path('decor/', views.DecorList.as_view(), name='decor_list'),
    path('decor/<slug:slug>', views.DecorDetail.as_view(), name='decor_detail'),
    path('costumes/', views.CostumeList.as_view(), name='costume_list'),
    path('costume/<slug:slug>', views.CostumeDetail.as_view(), name='costume_detail'),
    path('accessories/', views.AccessoriesList.as_view(), name='accessories_list'),
    path('accessories/<slug:slug>', views.AccessoriesDetail.as_view(), name='accessories_detail'),
    path('stylists/', views.StylistList.as_view(), name='stylist_list'),
    path('stylist/<slug:slug>', views.StylistDetail.as_view(), name='stylist_detail'),
    path('photo-studios/', views.PhotoStudioList.as_view(), name='photostudio_list'),
    path('photo-studio/<slug:slug>', views.PhotoStudioDetail.as_view(), name='photostudio_detail'),
    path('dance/', views.DanceList.as_view(), name='dance_list'),
    path('dance/<slug:slug>', views.DanceDetail.as_view(), name='dance_detail'),
    path('agencies/', views.AgencyList.as_view(), name='agency_list'),
    path('agency/<slug:slug>', views.AgencyDetail.as_view(), name='agency_detail'),
    path('create-review/', views.create_review, name='create_review'),
    path('create-portfolio/', views.add_portfolio, name='create_portfolio'),
    path('extend-portfolio/', views.extend_portfolio, name='extend_portfolio'),
    path('delete-portfolio/', views.delete_portfolio, name='delete_portfolio'),
]