# Generated by Django 4.0 on 2022-01-31 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0007_alter_clientprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='account.user')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_specialists', to='account.user')),
            ],
            options={
                'verbose_name': 'Избранный специалист',
                'verbose_name_plural': 'Избранные специалисты',
            },
        ),
    ]
